### ISSUE TITLE
Address Book fragment crash

### ISSUE THREAD

**Issue by hank** [hank/litecoin-wallet#10]
```
=== application info ===

Version: 1.03 (10003)
Package: de.schildbach.wallet.litecoin
Databases: address_book address_book-journal

Contents of FilesDir /data/data/de.schildbach.wallet.litecoin/files:
2013-04-04 19:48:54     4096  files
  - 2013-04-04 19:48:55      156  key-backup-base58
  - 2013-04-04 19:48:54      146  wallet-protobuf
  - 2013-04-04 19:48:55      156  key-backup-base58.99

Contents of CacheDir /data/data/de.schildbach.wallet.litecoin/cache:
2013-04-04 19:48:55     4096  cache
  - 2013-04-04 19:47:31     4096  com.android.renderscript.cache


=== stack trace ===

java.lang.RuntimeException: Unable to start activity ComponentInfo{de.schildbach.wallet.litecoin/de.schildbach.wallet.litecoin.ui.AddressBookActivity}: android.view.InflateException: Binary XML file line #35: Error inflating class fragment
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2100)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2125)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3553)
at android.app.ActivityThread.access$700(ActivityThread.java:140)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1233)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4898)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #35: Error inflating class fragment
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:308)
at com.actionbarsherlock.internal.ActionBarSherlockNative.setContentView(ActionBarSherlockNative.java:119)
at com.actionbarsherlock.app.SherlockFragmentActivity.setContentView(SherlockFragmentActivity.java:251)
at de.schildbach.wallet.litecoin.ui.AddressBookActivity.onCreate(AddressBookActivity.java:61)
at android.app.Activity.performCreate(Activity.java:5206)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1083)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2064)
... 12 more
Caused by: java.lang.IllegalStateException: Fragment de.schildbach.wallet.litecoin.ui.WalletAddressesFragment did not create a view.
at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:293)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:676)
... 25 more

Cause:

android.view.InflateException: Binary XML file line #35: Error inflating class fragment
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:308)
at com.actionbarsherlock.internal.ActionBarSherlockNative.setContentView(ActionBarSherlockNative.java:119)
at com.actionbarsherlock.app.SherlockFragmentActivity.setContentView(SherlockFragmentActivity.java:251)
at de.schildbach.wallet.litecoin.ui.AddressBookActivity.onCreate(AddressBookActivity.java:61)
at android.app.Activity.performCreate(Activity.java:5206)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1083)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2064)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2125)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3553)
at android.app.ActivityThread.access$700(ActivityThread.java:140)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1233)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4898)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalStateException: Fragment de.schildbach.wallet.litecoin.ui.WalletAddressesFragment did not create a view.
at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:293)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:676)
... 25 more

Cause:

java.lang.IllegalStateException: Fragment de.schildbach.wallet.litecoin.ui.WalletAddressesFragment did not create a view.
at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:293)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:676)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:308)
at com.actionbarsherlock.internal.ActionBarSherlockNative.setContentView(ActionBarSherlockNative.java:119)
at com.actionbarsherlock.app.SherlockFragmentActivity.setContentView(SherlockFragmentActivity.java:251)
at de.schildbach.wallet.litecoin.ui.AddressBookActivity.onCreate(AddressBookActivity.java:61)
at android.app.Activity.performCreate(Activity.java:5206)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1083)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2064)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2125)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3553)
at android.app.ActivityThread.access$700(ActivityThread.java:140)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1233)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4898)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
at dalvik.system.NativeStart.main(Native Method)


=== device info ===

Date: Thu Apr 04 19:49:01 AEST 2013
Phone Model: GT-I9300
Android Version: 4.1.2
Board: smdk4x12
Brand: samsung
Device: m0
Display: JZO54K.I9300XXEMA2
Finger Print: samsung/m0xx/m0:4.1.2/JZO54K/I9300XXEMA2:user/release-keys
Host: SEP-97
ID: JZO54K
Model: GT-I9300
Product: m0xx
Tags: release-keys
Time: 1358227330000
Type: user
User: se.infra
Configuration: {1 0 1.0 505mcc2mnc en_AU sw360dp w360dp h615dp nrml long port finger -keyb/v/h -nav/h s.7}
Screen Layout: size 2 long 32
Display Metrics: DisplayMetrics{density=2.0, width=720, height=1280, scaledDensity=2.0, xdpi=304.8, ydpi=306.71698}
Memory Class: 64
```

**Comment by hank** [comment]
This is what kills it:

``` java
setContentView(R.layout.address_book_content);
```

Not sure why yet...

After looking a bit more, it turns out the value maps differently depending on the values XML.  This seemed to map to address_book_twopanes, since the single pane one is too short to have a line 35.  

WalletAddressesFragment seems to have no onCreateView method, which might definitely be the problem here.  For now, I'll be removing this to prevent app crash.
