### ISSUE TITLE
RejectedExecutionException

### ISSUE THREAD

**Issue by hank** [hank/litecoin-wallet#11]
Not sure exactly how to fix this yet...

```
=== application info ===

Version: 1.03 (10003)
Package: de.schildbach.wallet.litecoin
Databases: address_book address_book-journal

Contents of FilesDir /data/data/de.schildbach.wallet.litecoin/files:
2013-04-08 08:19:14     4096  files
  - 2013-04-08 03:50:54      230  key-backup-base58
  - 2013-04-08 08:19:14    67841  wallet-protobuf
  - 2013-04-05 17:03:57      230  key-backup-base58.00
  - 2013-04-06 16:05:37      230  key-backup-base58.01
  - 2013-04-07 18:52:05      230  key-backup-base58.02
  - 2013-04-08 03:50:54      230  key-backup-base58.03

Contents of CacheDir /data/data/de.schildbach.wallet.litecoin/cache:
2013-04-08 08:18:59     4096  cache
  - 2013-04-04 21:47:23     4096  com.android.renderscript.cache
  - 2013-04-05 01:21:29   196677  application-log-1932275940.tmp
  - 2013-04-05 01:21:29      522  wallet-dump-1884208109.tmp


=== stack trace ===

java.util.concurrent.RejectedExecutionException: Task android.support.v4.content.ModernAsyncTask$3@42b972b8 rejected from java.util.concurrent.ThreadPoolExecutor@428019c8[Running, pool size = 128, active threads = 128, queued tasks = 10, completed tasks = 4342]
at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:1967)
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:782)
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1303)
at android.support.v4.content.ModernAsyncTask.executeOnExecutor$46741b06(ModernAsyncTask.java:423)
at android.support.v4.content.AsyncTaskLoader.executePendingTask(AsyncTaskLoader.java:195)
at android.support.v4.content.AsyncTaskLoader.onForceLoad(AsyncTaskLoader.java:115)
at android.support.v4.content.Loader.forceLoad(Loader.java:217)
at de.schildbach.wallet.litecoin.ui.TransactionsListFragment$TransactionsLoader$1.onThrotteledWalletChanged(TransactionsListFragment.java:361)
at de.schildbach.wallet.litecoin.util.ThrottelingWalletChangeListener$1.run(ThrottelingWalletChangeListener.java:92)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4918)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:771)
at dalvik.system.NativeStart.main(Native Method)


=== device info ===

Date: Mon Apr 08 08:19:27 EDT 2013
Phone Model: SAMSUNG-SGH-I747
Android Version: 4.1.1
Board: MSM8960
Brand: samsung
Device: d2att
Display: JRO03L.I747UCDLK3
Finger Print: samsung/d2uc/d2att:4.1.1/JRO03L/I747UCDLK3:user/release-keys
Host: SEP-103
ID: JRO03L
Model: SAMSUNG-SGH-I747
Product: d2uc
Tags: release-keys
Time: 1352962607000
Type: user
User: se.infra
Configuration: {0 1.0 310mcc410mnc en_US sw360dp w360dp h615dp nrml long port finger -keyb/v/h -nav/h s.53}
Screen Layout: size 2 long 32
Display Metrics: DisplayMetrics{density=2.0, width=720, height=1280, scaledDensity=2.0, xdpi=304.8, ydpi=303.85046}
Memory Class: 64
```

**Comment by hank** [comment]
I haven't seen a bug report like this for a LONG time, so I'm calling this fixed.
