### ISSUE TITLE
NullPointerException ExchangeRatesProvider.java:126

### ISSUE THREAD

**Issue by hank** [hank/litecoin-wallet#13]
=== application info ===

Version: 1.04 (10004)
Package: de.schildbach.wallet.litecoin
Databases:

Contents of FilesDir /data/data/de.schildbach.wallet.litecoin/files:
2013-04-09 22:22:54     4096  files
- 2013-04-09 23:03:31      156  key-backup-base58
- 2013-04-09 22:22:54      147  wallet-protobuf
- 2013-04-09 23:03:31      156  key-backup-base58.04

Contents of CacheDir /data/data/de.schildbach.wallet.litecoin/cache:
2013-04-09 23:03:31     4096  cache
- 2013-04-09 21:11:01     4096  com.android.renderscript.cache
- 2013-04-09 21:11:14      304  C4B3BBF7511882A1.toc
- 2013-04-09 21:11:14     8733  C4B3BBF7511882A1.bin
- 2013-04-09 23:03:10     7780  application-log-988245372.tmp

=== stack trace ===

java.lang.RuntimeException: An error occured while executing doInBackground()
at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:137)
at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:864)
Caused by: java.lang.NullPointerException
at de.schildbach.wallet.litecoin.ExchangeRatesProvider.query(ExchangeRatesProvider.java:126)
at android.content.ContentProvider.query(ContentProvider.java:673)
at android.content.ContentProvider$Transport.query(ContentProvider.java:210)
at android.content.ContentResolver.query(ContentResolver.java:375)
at android.content.ContentResolver.query(ContentResolver.java:318)
at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:35)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground$42af7916(AsyncTaskLoader.java:40)
at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
... 4 more

Cause:

java.lang.NullPointerException
at de.schildbach.wallet.litecoin.ExchangeRatesProvider.query(ExchangeRatesProvider.java:126)
at android.content.ContentProvider.query(ContentProvider.java:673)
at android.content.ContentProvider$Transport.query(ContentProvider.java:210)
at android.content.ContentResolver.query(ContentResolver.java:375)
at android.content.ContentResolver.query(ContentResolver.java:318)
at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:35)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground$42af7916(AsyncTaskLoader.java:40)
at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:864)

=== device info ===

Date: Tue Apr 09 23:03:33 CEST 2013
Phone Model: HTC One X
Android Version: 4.1.1
Board: unknown
Brand: htc_europe
Device: endeavoru
Display: JRO03C
Finger Print: htc_europe/endeavoru/endeavoru:4.1.1/JRO03C/156838.1:user/release-keys
Host: abm032
ID: JRO03C
Model: HTC One X
Product: endeavoru
Tags: release-keys
Time: 1360915958000
Type: user
User: unknown
Configuration: {1.0 238mcc1mnc da_DK sw360dp w360dp h615dp nrml long port finger -keyb/v/h -nav/h s.5 skin=default fontsize=3}
Screen Layout: size 2 long 32
Display Metrics: DisplayMetrics{density=2.0, width=720, height=1280, scaledDensity=2.0, xdpi=345.0566, ydpi=342.23157}
Memory Class: 64

**Comment by hank** [comment]
Wrapped this in a try/catch.  Shouldn't be an issue again.
