### ISSUE TITLE
RejectedExecutionException

### ISSUE THREAD

**Issue by hank** [hank/litecoin-wallet#16]
Not sure about the best way to handle this...

``````
Random crash


=== application info ===

Version: 1.05 (10006)
Package: de.schildbach.wallet.litecoin
Databases: address_book address_book-journal

Contents of FilesDir /data/data/de.schildbach.wallet.litecoin/files:
2013-04-18 07:04:00     4096  files
  - 2013-04-18 01:18:32      304  key-backup-base58
  - 2013-04-18 07:04:00   435636  wallet-protobuf
  - 2013-04-17 19:05:29      304  key-backup-base58.12
  - 2013-04-18 01:18:32      304  key-backup-base58.13

Contents of CacheDir /data/data/de.schildbach.wallet.litecoin/cache:
2013-04-18 07:03:46     4096  cache
  - 2013-04-16 22:45:15     4096  com.android.renderscript.cache


=== stack trace ===

java.util.concurrent.RejectedExecutionException: Task android.support.v4.content.ModernAsyncTask$3@43134f10 rejected from java.util.concurrent.ThreadPoolExecutor@42e62ac8[Running, pool size = 128, active threads = 127, queued tasks = 10, completed tasks = 65783]
at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:1967)
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:782)
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1303)
at android.support.v4.content.ModernAsyncTask.executeOnExecutor$46741b06(ModernAsyncTask.java:423)
at android.support.v4.content.AsyncTaskLoader.executePendingTask(AsyncTaskLoader.java:195)
at android.support.v4.content.AsyncTaskLoader.onForceLoad(AsyncTaskLoader.java:115)
at android.support.v4.content.Loader.forceLoad(Loader.java:217)
at de.schildbach.wallet.litecoin.ui.TransactionsListFragment$TransactionsLoader$1.onThrotteledWalletChanged(TransactionsListFragment.java:361)
at de.schildbach.wallet.litecoin.util.ThrottelingWalletChangeListener$1.run(ThrottelingWalletChangeListener.java:92)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4918)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:771)
at dalvik.system.NativeStart.main(Native Method)


=== device info ===

Date: Thu Apr 18 07:04:16 EDT 2013
Phone Model: SAMSUNG-SGH-I747
Android Version: 4.1.1
Board: MSM8960
Brand: samsung
Device: d2att
Display: JRO03L.I747UCDLK3
Finger Print: samsung/d2uc/d2att:4.1.1/JRO03L/I747UCDLK3:user/release-keys
Host: SEP-103
ID: JRO03L
Model: SAMSUNG-SGH-I747
Product: d2uc
Tags: release-keys
Time: 1352962607000
Type: user
User: se.infra
Configuration: {0 1.0 310mcc410mnc en_US sw360dp w360dp h615dp nrml long port finger -keyb/v/h -nav/h s.149}
Screen Layout: size 2 long 32
Display Metrics: DisplayMetrics{density=2.0, width=720, height=1280, scaledDensity=2.0, xdpi=304.8, ydpi=303.85046}
Memory Class: 64```
``````

**Comment by hank** [comment]
http://stackoverflow.com/a/11173990

**Comment by hank** [comment]
Duplicate of #11
