### ISSUE TITLE
Unresponsive after adding local peer

### ISSUE THREAD

**Issue by hank** [hank/litecoin-wallet#17]
I added a lan IP as a trusted peer and then it became unresponsive

=== application info ===

Version: 1.05 (10006)
Package: de.schildbach.wallet.litecoin
Databases: webview.db webview.db-journal webviewCookiesChromium.db address_book address_book-journal

Contents of FilesDir /data/data/de.schildbach.wallet.litecoin/files:
2013-04-26 10:15:40     4096  files
- 2013-04-26 10:14:53      156  key-backup-base58
- 2013-04-26 10:15:40      146  wallet-protobuf
- 2013-04-26 10:14:53      156  key-backup-base58.21

Contents of CacheDir /data/data/de.schildbach.wallet.litecoin/cache:
2013-04-26 10:14:55     4096  cache
- 2013-04-26 10:10:54     4096  com.android.renderscript.cache
- 2013-04-26 10:11:15    23859  com.android.opengl.shaders_cache
- 2013-04-26 10:11:11     4096  webviewCacheChromiumStaging

=== stack trace ===

android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@41c32b90 is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:567)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:246)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2806)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2235)
        at android.app.ActivityThread.access$600(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5039)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)

=== device info ===

Date: Fri Apr 26 10:15:40 EDT 2013
Phone Model: Galaxy Nexus
Android Version: 4.2.1
Board: tuna
Brand: samsung
Device: maguro
Display: JOP40D.I9250UGMA2
Finger Print: samsung/yakjuux/maguro:4.2.1/JOP40D/I9250UGMA2:user/release-keys
Host: DELL123
ID: JOP40D
Model: Galaxy Nexus
Product: yakjuux
Tags: release-keys
Time: 1359339951000
Type: user
User: dpi.sec
Configuration: {1.0 302mcc610mnc en_US ldltr sw360dp w360dp h567dp 320dpi nrml port finger -keyb/v/h -nav/h s.248}
Screen Layout: size 2 long 16
Display Metrics: DisplayMetrics{density=2.0, width=720, height=1184, scaledDensity=2.0, xdpi=315.31033, ydpi=318.7451}
Memory Class: 96

PUT ADDITIONAL COMMENTS TO THE TOP. DOWN HERE NOBODY WILL NOTICE.

**Comment by bigconvience** [comment]
Is it resolved
