### ISSUE TITLE
Crash on non-numeric conversion

### ISSUE THREAD

**Issue by hank** [hank/litecoin-wallet#4]
Need to sanitize strings before sending to nanocoin conversion.

```
=== application info ===

Version: 1.02 (10002)
Package: de.schildbach.wallet.litecoin
Databases:

Contents of FilesDir /data/data/de.schildbach.wallet.litecoin/files:
2013-04-02 17:56:21     4096  files
  - 2013-04-02 17:57:23      156  key-backup-base58
  - 2013-04-02 17:56:21      109  wallet-protobuf
  - 2013-04-02 17:57:23      156  key-backup-base58.97

Contents of CacheDir /data/data/de.schildbach.wallet.litecoin/cache:
2013-04-02 17:57:23     4096  cache
  - 2013-04-02 17:56:19     4096  com.android.renderscript.cache

=== stack trace ===

java.lang.RuntimeException: An error occured while executing doInBackground()
at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:137)
at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.NumberFormatException: Invalid long: "2,595150"
at java.lang.Long.invalidLong(Long.java:125)
at java.lang.Long.parse(Long.java:362)
at java.lang.Long.parseLong(Long.java:353)
at java.lang.Long.parseLong(Long.java:319)
at java.math.BigDecimal.<init>(BigDecimal.java:350)
at java.math.BigDecimal.<init>(BigDecimal.java:438)
at com.google.litecoin.core.Utils.toNanoCoins(Utils.java:110)
at de.schildbach.wallet.litecoin.ExchangeRatesProvider.getLitecoinCharts(ExchangeRatesProvider.java:187)
at de.schildbach.wallet.litecoin.ExchangeRatesProvider.query(ExchangeRatesProvider.java:95)
at android.content.ContentProvider.query(ContentProvider.java:652)
at android.content.ContentProvider$Transport.query(ContentProvider.java:189)
at android.content.ContentResolver.query(ContentResolver.java:372)
at android.content.ContentResolver.query(ContentResolver.java:315)
at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:35)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground$42af7916(AsyncTaskLoader.java:40)
at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
... 4 more

Cause:

java.lang.NumberFormatException: Invalid long: "2,595150"
at java.lang.Long.invalidLong(Long.java:125)
at java.lang.Long.parse(Long.java:362)
at java.lang.Long.parseLong(Long.java:353)
at java.lang.Long.parseLong(Long.java:319)
at java.math.BigDecimal.<init>(BigDecimal.java:350)
at java.math.BigDecimal.<init>(BigDecimal.java:438)
at com.google.litecoin.core.Utils.toNanoCoins(Utils.java:110)
at de.schildbach.wallet.litecoin.ExchangeRatesProvider.getLitecoinCharts(ExchangeRatesProvider.java:187)
at de.schildbach.wallet.litecoin.ExchangeRatesProvider.query(ExchangeRatesProvider.java:95)
at android.content.ContentProvider.query(ContentProvider.java:652)
at android.content.ContentProvider$Transport.query(ContentProvider.java:189)
at android.content.ContentResolver.query(ContentResolver.java:372)
at android.content.ContentResolver.query(ContentResolver.java:315)
at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:35)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground$42af7916(AsyncTaskLoader.java:40)
at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:856)

=== device info ===

Date: Tue Apr 02 17:57:33 CEST 2013
Phone Model: GT-I9305
Android Version: 4.1.1
Board: smdk4x12
Brand: samsung
Device: m3
Display: JRO03C.I9305XXALK5
Finger Print: samsung/m3xx/m3:4.1.1/JRO03C/I9305XXALK5:user/release-keys
Host: DELL218
ID: JRO03C
Model: GT-I9305
Product: m3xx
Tags: release-keys
Time: 1352990753000
Type: user
User: dpi
Configuration: {1 0 1.0 238mcc20mnc da_DK sw360dp w360dp h615dp nrml long port finger -keyb/v/h -nav/h s.35}
Screen Layout: size 2 long 32
Display Metrics: DisplayMetrics{density=2.0, width=720, height=1280, scaledDensity=2.0, xdpi=304.8, ydpi=306.71698}
Memory Class: 64
```

**Comment by hank** [comment]
Fixed with this code:

``` java
                    String euros = String.format("%.4f", avg);
                    // Fix things like 3,1250
                    euros = euros.replace(",", ".");
```

Unable to reproduce bug - I'm pretty sure it's related to comma-delimited floating point numbers.  This will go into the next release.

**Comment by hank** [comment]
Apparently this is still occurring on 1.03.
